### PR TITLE
Added Meteor integration.

### PR DESCRIPTION
**Pull request by timbrandin**
I've set it up a blueimp organization and blueimp:javascript-load-image on Meteor.com, contact me to get organizations permissions for blueimp organization account.

### CODE REVIEW

**Comment by timbrandin** [comment]
https://atmospherejs.com/blueimp/javascript-load-image

**Comment by blueimp** [comment]
Thanks for your contribution, @timbrandin!
I'm fond of Meteor, but reluctant to add any additional maintenance overhead as I'm currently not an active Meteor user and wouldn't be able to test for each release.
Would it be feasible that you maintain the Meteor package definitions in your fork?

**Comment by timbrandin** [comment]
No problems on that! Cheers, // T

2015-07-29 14:56 GMT+02:00 Sebastian Tschan <notifications@github.com>:

> Thanks for your contribution, @timbrandin <https://github.com/timbrandin>!
> I'm fond of Meteor, but reluctant to add any additional maintenance
> overhead as I'm currently not an active Meteor user and wouldn't be able to
> test for each release.
> Would it be feasible that you maintain the Meteor package definitions in
> your fork?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/blueimp/JavaScript-Load-Image/pull/68#issuecomment-125940963>
> .
>



-- 
Cheers,
// Tim Brandin @timbrandin <https://twitter.com/#!/timbrandin>
http://timbrandin.com
http://studiointeract.com

**Comment by blueimp** [comment]
Thanks for your understanding!

**Pull request closed without merging**
