### PR TITLE
fix crop with downsamplingRatio

### PR DESCRIPTION
**Pull request by fleg**
It not actually broken, because I can't get canvas data (Tainted canvases may not be exported).
I append cropped image to body, and it transparent, but it should be black.

I think, bug in [renderImageToCanvas](https://github.com/blueimp/JavaScript-Load-Image/blob/master/js/load-image.js#L279-L280) calling with non-zero `sourceX` and `sourceY` in cycle, and image just moving out beyond the border of canvas.

If you agree, I can fix it, but I don't know how to check content of cropped image in test

### CODE REVIEW

**Comment by blueimp** [comment]
Thanks for your contribution, @fleg 

To check the content of the image, you'll need to [retrieve the canvas Image data](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/getImageData).
You'll get back an [ImageData object](https://developer.mozilla.org/en-US/docs/Web/API/ImageData) with a `data` property representing a one-dimensional array containing the data in the RGBA order, with integer values between 0 and 255 (included).

**Comment by fleg** [comment]
`getImageData` throws error in browser (because of `file:///` protocol), but if perfectly working in phantomjs, and now test failing

**Comment by fleg** [comment]
I fix scale, but it hard to test this feature with single colored image

**Comment by blueimp** [comment]
Thanks, I think your test is sufficient.

Just one note regarding your fix:
Instead of introducing another variable (`cropped`), please simply add the following two lines after the first `loadImage.renderImageToCanvas` call in the downsampling loop:

```js
          sourceX = 0
          sourceY = 0
```

After this change, please squash your commits into one (or two if you want to add the test separately).
Then I'll merge your changes gladly. :)

**Comment by fleg** [comment]
done

**Comment by blueimp** [comment]
Perfect, thanks!

**Pull request merged**
