### PR TITLE
Optimisation for thumbnail

### PR DESCRIPTION
**Pull request by bubbatls**
There is no need to rebuild a data uri.
We can use URL.createObjectURL and a Blob.
It is faster, and further use of the URL will be too.

### CODE REVIEW

**Comment by blueimp** [comment]
Thanks @bubbatls 
Could you update your pull request so it passes the linter rules?

**Comment by bubbatls** [comment]
Sorry, I've worked too fast and so... too dirty.
It's done

**Comment by blueimp** [comment]
Thanks again. :)

**Comment by bubbatls** [comment]
maybe the code for building data-uri might be used in loadImage.createObjectURL when it is detected it does not work properly

**Comment by blueimp** [comment]
Could you clarify what you meany by "it does not work properly"?

**Comment by bubbatls** [comment]
The variable urlAPI might be undefined if it is not available or buggy (for opera 12 as I saw in comments)
And the data-uri might solve the issue, but maybe it is a bad idea to potentielly use it for something bigger than a thumbnail

**Comment by blueimp** [comment]
The EXIF code is only called in browsers that do support `DataView`.
Opera 12 is an edge case, but I don't think this browser is even supported anymore.
There's still Safari 6 (and potentially other browsers using `webkitURL`), but that is solved by using `loadImage.createObjectURL`.

**Comment by bubbatls** [comment]
Thanks for the explanation,
And thanks for this project

**Pull request merged**
