### PR TITLE
Added support for use with webpack

### PR DESCRIPTION
**Pull request by ruscoder**

### CODE REVIEW

**Comment by blueimp** [comment]
Could you elaborate why the current version of this project doesn't already fit in with webpack?

**Comment by blueimp** [comment]
Closing for now, as this will need a rebase on the latest changes.

**Comment by micky2be** [comment]
I currently cannot require submodule of your loader using webpack.
For example using `import loadImage from 'blueimp-load-image/js/load-image-orientation';`

This PR fixes the problem.

**Comment by blueimp** [comment]
Thanks @ruscoder, I've finally merged this, thanks to @micky2be's rebase.

**Pull request closed without merging**
