### PR TITLE
Webpack support

### PR DESCRIPTION
**Pull request by micky2be**
Updated PR #72 

The Webpack community is big. Would be nice to to support it.

[Review on Reviewable](https://reviewable.io/reviews/blueimp/javascript-load-image/75)

### CODE REVIEW

**Comment by rlmcneary2** [comment]
Can confirm that making these changes gets the npm package working with webpack. Without them the npm package can't be required successfully. (webpack v1.12.12).

**Comment by micky2be** [comment]
I confirm.
I currently use this version for my project.

**Comment by c0cky** [comment]
yes please merge + 1

**Comment by re6exp** [comment]
+1

**Comment by siccc** [comment]
+1

**Comment by blueimp** [comment]
Thanks for your contribution, @micky2be.

**Pull request merged**
